### ISSUE TITLE
Use on different internet connection

### ISSUE THREAD

**Issue by saitenkun** [qH0sT/AndroSpy#72]
Greetings!

Im currently running on v3 and i was able to use the app with no issues on the same internet network the device was connected however I’m away on vacation and the device no longer shows i have access to the current Router I am using and haven’t changed any connection settings on my computer. The way i set up the build was pretty much set up my pc’s ip as Static (same pc im using now) and used the IPv4 with a port number and on the Router (the one that is connected/provides interesting to the device) i set up a “Virtual server/Port forwarding” with the same IPv4 and Port. Do i need to change any settings on my current Router (same model as the one connected to the device)? Change settings on my pc? I didn’t use any external port pages or anything as last time i tried that it was waaaay slow.

any help would be greatly appreciated!
Sorry for the long read

**Comment by qH0sT** [comment]
You should fix the IPv4 adress like image, otherwise your IPv4 will change after PC reboot:

![0](https://user-images.githubusercontent.com/45147475/110957823-10ae7d00-835d-11eb-9205-e233003e2d72.PNG)

**Comment by saitenkun** [comment]
Greetings,

i just checked and it is in fact just as applied it, its still static ip and the same ip i used on the build. I checked as well in cmd ipconfig and the IPv4 shows the same ip i applied on the build, i did find it curious that i checked online (yougetsignal) to see if my port was “open” and it shows as “closed” but I believe i opened it on my current router as well as the router that the device is connected to. 

any suggestions?

thanks for your time

**Comment by qH0sT** [comment]
> Greetings,
> 
> i just checked and it is in fact just as applied it, its still static ip and the same ip i used on the build. I checked as well in cmd ipconfig and the IPv4 shows the same ip i applied on the build, i did find it curious that i checked online (yougetsignal) to see if my port was “open” and it shows as “closed” but I believe i opened it on my current router as well as the router that the device is connected to.
> 
> any suggestions?
> 
> thanks for your time

Did you reboot the phone for checking connection? Reboot phone and look if connection will come or not. If connection comes, then download latest release of androspy from github.(I have fixed a minimal bug.) If connection don't come, check your Router port forwarding settings.

**Comment by saitenkun** [comment]
Im connected through ethernet.

Should i change my routers WAN setup to static with the same IP as the IPv4?

I see my router has a “port trigger” option, should i add the port?

i did notice that the port checker has a different ip than my IPv4 when i click “use current IP” i used the current and as well the IPv4 and still shows the port i used as “closed”

**Comment by qH0sT** [comment]
> Im connected through ethernet.
> 
> Should i change my routers WAN setup to static with the same IP as the IPv4?
> 
> I see my router has a “port trigger” option, should i add the port?
> 
> i did notice that the port checker has a different ip than my IPv4 when i click “use current IP” i used the current and as well the IPv4 and still shows the port i used as “closed”

https://github.com/qH0sT/AndroSpy/issues/72#issuecomment-797707285

**Comment by saitenkun** [comment]
Thank you for the quick response

Both Routers have been updated with  "virtual server/port forwarding" option using the IPv4 and Port i used for Build.

If i get connection, do i need to re-install Build to device after i update the V3 on my computer?

The routers i have are provided by my ISP, I own another router should, i connect the router to the one provided by my ISP and connect it to my PC and set the router to static IP with same Ip as IPv4? And open ports with that one?

**Comment by qH0sT** [comment]
> Thank you for the quick response
> 
> Both Routers have been updated with "virtual server/port forwarding" option using the IPv4 and Port i used for Build.
> 
> If i get connection, do i need to re-install Build to device after i update the V3 on my computer?
> 
> The routers i have are provided by my ISP, I own another router should, i connect the router to the one provided by my ISP and connect it to my PC and set the router to static IP with same Ip as IPv4? And open ports with that one?

"If i get connection, do i need to re-install Build to device after i update the V3 on my computer?"

-Yes

"The routers i have are provided by my ISP, I own another router should, i connect the router to the one provided by my ISP and connect it to my PC and set the router to static IP with same Ip as IPv4? And open ports with that one?"

-I don't understand this, Only one rule: IPv4 in Builder and IPv4 of PC must be same

**Comment by saitenkun** [comment]
Perfect!

So we pretty much covered that,
regardless of where im connected on the internet:

•IPv4 on Build is same as IPv4 on Pc 
•Port chosen  is “open” on BOTH routers 

This is pretty much what i have set up.

Is there any video tutorial that you can recommend for port forwarding without the use of external websites (ngork, portmap,etc..) ? 
I understand how to do builds but the Port Forwarding part gets confusing.

Thanks again for everything!

**Comment by qH0sT** [comment]
> Perfect!
> 
> So we pretty much covered that,
> regardless of where im connected on the internet:
> 
> •IPv4 on Build is same as IPv4 on Pc
> •Port chosen is “open” on BOTH routers
> 
> This is pretty much what i have set up.
> 
> Is there any video tutorial that you can recommend for port forwarding without the use of external websites (ngork, portmap,etc..) ?
> I understand how to do builds but the Port Forwarding part gets confusing.
> 
> Thanks again for everything!

did you receive connection on panel after reboot Phone?

**Comment by saitenkun** [comment]
Unfortunately I don't have access to the device still as i am away, this is why I mentioned 2 routers (one connected to the device and one connected to my computer) and both have the port on build as well as IPv4 open in the router settings. 

It could just be that the device is off tbh. I just wanted to make sure that if im away from the same network connection as the device is connected to i could still access it. I created the build on my laptop that is connected to my current router and has static IPv4

So to be clear regardless of where i am located, as long as i:

•Have internet access
•IPv4 same as Build
•Port and IPv4 is "Open" on 1 or both routers
•Device is turned on and connected to the internet

I SHOULD be able to see connection, correct?

Thank you again for taking your time to reply. It is greatly appreciated.

**Comment by qH0sT** [comment]
> Unfortunately I don't have access to the device still as i am away, this is why I mentioned 2 routers (one connected to the device and one connected to my computer) and both have the port on build as well as IPv4 open in the router settings.
> 
> It could just be that the device is off tbh. I just wanted to make sure that if im away from the same network connection as the device is connected to i could still access it. I created the build on my laptop that is connected to my current router and has static IPv4
> 
> So to be clear regardless of where i am located, as long as i:
> 
> •Have internet access
> •IPv4 same as Build
> •Port and IPv4 is "Open" on 1 or both routers
> •Device is turned on and connected to the internet
> 
> I SHOULD be able to see connection, correct?
> 
> Thank you again for taking your time to reply. It is greatly appreciated.

you must be in same network with main router. No away from the same network.

**Comment by saitenkun** [comment]
Aaah :( i see! So if i wanted the build to work outside of the same network I'd need to create a build with an external Port website (ngrok,Portmap,etc.)? Any recommendations?

**Comment by qH0sT** [comment]
> Aaah :( i see! So if i wanted the build to work outside of the same network I'd need to create a build with an external Port website (ngrok,Portmap,etc.)? Any recommendations?

Yes, you must use DNS Service for WAN connection. Like; ngrok, portmap.io, duckdns, no-ip etc.
